# Generated by Django 5.0.6 on 2024-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.TextField()),
                ('size', models.TextField()),
                ('breed', models.TextField()),
                ('age', models.IntegerField()),
                ('characteristics', models.TextField()),
                ('overall_health', models.TextField()),
                ('child_friendly', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
