# Generated by Django 5.0.6 on 2024-06-28 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small (1-10 kg)'), ('Medium', 'Medium (11-26 kg)'), ('Large', 'Large (27-45 kg)'), ('Extra-Large', 'Extra-Large (46+ kg)')], max_length=40, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('characteristics', models.TextField()),
                ('overall_health', models.TextField()),
                ('good_in_home_with', models.CharField(blank=True, choices=[('children < 5', 'children under 5 years old'), ('children < 12', 'children under 12 years old'), ('all age children ', 'children of all ages'), ('no children ', 'can not handle the stress of children')], max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('rejected', models.BooleanField(default=False, verbose_name='Rejected')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
