# Generated by Django 5.0.6 on 2024-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='banner',
            field=models.ImageField(blank=True, default='../../static/img/fallback.png', upload_to=''),
        ),
    ]
