# Generated by Django 5.0.6 on 2024-06-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_name',
            new_name='name',
        ),
    ]
