# Generated by Django 5.0.6 on 2024-06-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_pet_name_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small (1-10 kg)'), ('Medium', 'Medium (11-26 kg)'), ('Large', 'Large (27-45 kg)'), ('Extra-Large', 'Extra-Large (46+ kg)')], max_length=40, null=True),
        ),
    ]
