# Generated by Django 5.0.6 on 2024-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_breed_alter_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default=True, max_length=150),
        ),
    ]
