# Generated by Django 5.0.6 on 2024-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
