# Generated by Django 5.0.6 on 2024-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
