# Generated by Django 5.0.6 on 2024-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.PNG', upload_to='pets'),
        ),
    ]
