# Generated by Django 5.0.6 on 2024-08-25 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, default='fallback.PNG', max_length=255, verbose_name='pets'),
        ),
    ]
