# Generated by Django 5.0.6 on 2024-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='child_friendly',
        ),
        migrations.AddField(
            model_name='pet',
            name='good_in_home_with',
            field=models.CharField(blank=True, choices=[('children < 5', 'children under 5 years old'), ('children < 12', 'children under 12 years old'), ('all age children ', 'children of all ages'), ('no children ', 'can not handle the stress of children')], max_length=50, null=True),
        ),
    ]
