# Generated by Django 5.0.6 on 2024-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_remove_pet_child_friendly_pet_good_in_home_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
