# Generated by Django 5.0.6 on 2024-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_pet_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejected'),
        ),
    ]
