# Generated by Django 5.0.6 on 2024-06-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='animal',
            new_name='pet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitted_at',
        ),
    ]
