# Generated by Django 5.0.6 on 2024-06-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_rename_animal_application_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pets.pet'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
